name: Run scheduled action
on:
  schedule:
    # You need to set your schedule here
    - cron: "00 05 * * *"

jobs:
  create_issue:
    name: Pick_up_the_Umbrella_Reminder
    runs-on: ubuntu-latest
    env:
      ACCOUNT_SID: ${{ vars.ACCOUNT_SID }}
      API_KEY: ${{ vars.API_KEY }}
      AUTH_TOKEN: ${{ vars.AUTH_TOKEN }}
      MY_LAT: ${{ vars.MY_LAT }}
      MY_LONG: ${{ vars.MY_LONG }}
      RECEIVER: ${{ vars.RECEIVER }}
      SENDER: ${{ vars.SENDER }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run python
        run: python3 main.py
