name: Run scheduled action
on:
  schedule:
    # You need to set your schedule here
    - cron: "* 5 * * *"

jobs:
  create_issue:
    name: Send Birthday wish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run python
        run: python3 main.py
